/* eslint-disable camelcase */
export const APP_PROVIDERS_RAW = [
  {
    type: 'docker',
    version: '20230717',
    name: 'Docker',
    variant: {
      id: 'd5ff282b-dd1a-4c9a-a0c8-c9524b1370e9',
      slug: 'docker',
      name: 'Docker',
      deployType: 'docker',
      logo: 'https://assets.clever-cloud.com/logos/docker.svg',
    },
    description: 'Docker',
    enabled: true,
    comingSoon: false,
    maxInstances: 40,
    tags: [],
    deployments: [
      'git',
    ],
    flavors: [
      {
        name: 'nano',
        mem: 582,
        cpus: 1,
        gpus: 0,
        disk: null,
        price: 0.0083333333,
        available: true,
        microservice: true,
        machine_learning: false,
        nice: 5,
        price_id: 'apps.nano',
        memory: {
          unit: 'B',
          value: 536870912,
          formatted: '512 MiB',
        },
      },
      {
        name: 'XS',
        mem: 1152,
        cpus: 1,
        gpus: 0,
        disk: null,
        price: 0.0222222222,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.XS',
        memory: {
          unit: 'B',
          value: 1073741824,
          formatted: '1024 MiB',
        },
      },
      {
        name: 'S',
        mem: 2048,
        cpus: 2,
        gpus: 0,
        disk: null,
        price: 0.0444444444,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.S',
        memory: {
          unit: 'B',
          value: 2147483648,
          formatted: '2048 MiB',
        },
      },
      {
        name: 'M',
        mem: 4096,
        cpus: 4,
        gpus: 0,
        disk: null,
        price: 0.1055555556,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.M',
        memory: {
          unit: 'B',
          value: 4294967296,
          formatted: '4096 MiB',
        },
      },
      {
        name: 'L',
        mem: 8192,
        cpus: 6,
        gpus: 0,
        disk: null,
        price: 0.2111111111,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.L',
        memory: {
          unit: 'B',
          value: 8589934592,
          formatted: '8192 MiB',
        },
      },
      {
        name: 'XL',
        mem: 16384,
        cpus: 8,
        gpus: 0,
        disk: null,
        price: 0.4222222222,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.XL',
        memory: {
          unit: 'B',
          value: 17179869184,
          formatted: '16384 MiB',
        },
      },
      {
        name: '2XL',
        mem: 24576,
        cpus: 12,
        gpus: 0,
        disk: null,
        price: 0.6666666667,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.2XL',
        memory: {
          unit: 'B',
          value: 25769803776,
          formatted: '24576 MiB',
        },
      },
      {
        name: '3XL',
        mem: 32768,
        cpus: 16,
        gpus: 0,
        disk: null,
        price: 0.8888888889,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.3XL',
        memory: {
          unit: 'B',
          value: 34359738368,
          formatted: '32768 MiB',
        },
      },
    ],
    defaultFlavor: {
      name: 'XS',
      mem: 1152,
      cpus: 1,
      gpus: 0,
      disk: null,
      price: 0.0222222222,
      available: true,
      microservice: false,
      machine_learning: false,
      nice: 0,
      price_id: 'apps.XS',
      memory: {
        unit: 'B',
        value: 1073741824,
        formatted: '1024 MiB',
      },
    },
    buildFlavor: {
      name: 'S',
      mem: 2048,
      cpus: 2,
      gpus: 0,
      disk: null,
      price: 0.0444444444,
      available: true,
      microservice: false,
      machine_learning: false,
      nice: 0,
      price_id: 'apps.S',
      memory: {
        unit: 'B',
        value: 2147483648,
        formatted: '2048 MiB',
      },
    },
  },
  {
    type: 'dotnet',
    version: '20230719',
    name: '.NET core',
    variant: {
      id: '08af642a-e48c-40d0-9fc0-124ee9dc0535',
      slug: 'dotnet',
      name: '.NET core',
      deployType: 'dotnet',
      logo: 'https://assets.clever-cloud.com/logos/dotnet.svg',
    },
    description: '.NET Core',
    enabled: true,
    comingSoon: false,
    maxInstances: 40,
    tags: [
      'asp',
      'core',
      '.net',
    ],
    deployments: [
      'git',
    ],
    flavors: [
      {
        name: 'pico',
        mem: 326,
        cpus: 1,
        gpus: 0,
        disk: null,
        price: 0.0062500000,
        available: true,
        microservice: true,
        machine_learning: false,
        nice: 5,
        price_id: 'apps.pico',
        memory: {
          unit: 'B',
          value: 268435456,
          formatted: '256 MiB',
        },
      },
      {
        name: 'nano',
        mem: 582,
        cpus: 1,
        gpus: 0,
        disk: null,
        price: 0.0083333333,
        available: true,
        microservice: true,
        machine_learning: false,
        nice: 5,
        price_id: 'apps.nano',
        memory: {
          unit: 'B',
          value: 536870912,
          formatted: '512 MiB',
        },
      },
      {
        name: 'XS',
        mem: 1152,
        cpus: 1,
        gpus: 0,
        disk: null,
        price: 0.0222222222,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.XS',
        memory: {
          unit: 'B',
          value: 1073741824,
          formatted: '1024 MiB',
        },
      },
      {
        name: 'S',
        mem: 2048,
        cpus: 2,
        gpus: 0,
        disk: null,
        price: 0.0444444444,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.S',
        memory: {
          unit: 'B',
          value: 2147483648,
          formatted: '2048 MiB',
        },
      },
      {
        name: 'M',
        mem: 4096,
        cpus: 4,
        gpus: 0,
        disk: null,
        price: 0.1055555556,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.M',
        memory: {
          unit: 'B',
          value: 4294967296,
          formatted: '4096 MiB',
        },
      },
      {
        name: 'L',
        mem: 8192,
        cpus: 6,
        gpus: 0,
        disk: null,
        price: 0.2111111111,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.L',
        memory: {
          unit: 'B',
          value: 8589934592,
          formatted: '8192 MiB',
        },
      },
      {
        name: 'XL',
        mem: 16384,
        cpus: 8,
        gpus: 0,
        disk: null,
        price: 0.4222222222,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.XL',
        memory: {
          unit: 'B',
          value: 17179869184,
          formatted: '16384 MiB',
        },
      },
      {
        name: '2XL',
        mem: 24576,
        cpus: 12,
        gpus: 0,
        disk: null,
        price: 0.6666666667,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.2XL',
        memory: {
          unit: 'B',
          value: 25769803776,
          formatted: '24576 MiB',
        },
      },
      {
        name: '3XL',
        mem: 32768,
        cpus: 16,
        gpus: 0,
        disk: null,
        price: 0.8888888889,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.3XL',
        memory: {
          unit: 'B',
          value: 34359738368,
          formatted: '32768 MiB',
        },
      },
    ],
    defaultFlavor: {
      name: 'XS',
      mem: 1152,
      cpus: 1,
      gpus: 0,
      disk: null,
      price: 0.0222222222,
      available: true,
      microservice: false,
      machine_learning: false,
      nice: 0,
      price_id: 'apps.XS',
      memory: {
        unit: 'B',
        value: 1073741824,
        formatted: '1024 MiB',
      },
    },
    buildFlavor: {
      name: 'M',
      mem: 4096,
      cpus: 4,
      gpus: 0,
      disk: null,
      price: 0.1055555556,
      available: true,
      microservice: false,
      machine_learning: false,
      nice: 0,
      price_id: 'apps.M',
      memory: {
        unit: 'B',
        value: 4294967296,
        formatted: '4096 MiB',
      },
    },
  },
  {
    type: 'erlang',
    version: '20230719',
    name: 'Elixir',
    variant: {
      id: '9e23b9a8-d40e-41ad-9739-5d31b81e200e',
      slug: 'elixir',
      name: 'Elixir',
      deployType: 'erlang',
      logo: 'https://assets.clever-cloud.com/logos/elixir.svg',
    },
    description: 'Erlang applications',
    enabled: true,
    comingSoon: false,
    maxInstances: 40,
    tags: [],
    deployments: [
      'git',
    ],
    flavors: [
      {
        name: 'pico',
        mem: 326,
        cpus: 1,
        gpus: 0,
        disk: null,
        price: 0.0062500000,
        available: true,
        microservice: true,
        machine_learning: false,
        nice: 5,
        price_id: 'apps.pico',
        memory: {
          unit: 'B',
          value: 268435456,
          formatted: '256 MiB',
        },
      },
      {
        name: 'nano',
        mem: 582,
        cpus: 1,
        gpus: 0,
        disk: null,
        price: 0.0083333333,
        available: true,
        microservice: true,
        machine_learning: false,
        nice: 5,
        price_id: 'apps.nano',
        memory: {
          unit: 'B',
          value: 536870912,
          formatted: '512 MiB',
        },
      },
      {
        name: 'XS',
        mem: 1152,
        cpus: 1,
        gpus: 0,
        disk: null,
        price: 0.0222222222,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.XS',
        memory: {
          unit: 'B',
          value: 1073741824,
          formatted: '1024 MiB',
        },
      },
      {
        name: 'S',
        mem: 2048,
        cpus: 2,
        gpus: 0,
        disk: null,
        price: 0.0444444444,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.S',
        memory: {
          unit: 'B',
          value: 2147483648,
          formatted: '2048 MiB',
        },
      },
      {
        name: 'M',
        mem: 4096,
        cpus: 4,
        gpus: 0,
        disk: null,
        price: 0.1055555556,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.M',
        memory: {
          unit: 'B',
          value: 4294967296,
          formatted: '4096 MiB',
        },
      },
      {
        name: 'L',
        mem: 8192,
        cpus: 6,
        gpus: 0,
        disk: null,
        price: 0.2111111111,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.L',
        memory: {
          unit: 'B',
          value: 8589934592,
          formatted: '8192 MiB',
        },
      },
      {
        name: 'XL',
        mem: 16384,
        cpus: 8,
        gpus: 0,
        disk: null,
        price: 0.4222222222,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.XL',
        memory: {
          unit: 'B',
          value: 17179869184,
          formatted: '16384 MiB',
        },
      },
      {
        name: '2XL',
        mem: 24576,
        cpus: 12,
        gpus: 0,
        disk: null,
        price: 0.6666666667,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.2XL',
        memory: {
          unit: 'B',
          value: 25769803776,
          formatted: '24576 MiB',
        },
      },
      {
        name: '3XL',
        mem: 32768,
        cpus: 16,
        gpus: 0,
        disk: null,
        price: 0.8888888889,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.3XL',
        memory: {
          unit: 'B',
          value: 34359738368,
          formatted: '32768 MiB',
        },
      },
    ],
    defaultFlavor: {
      name: 'XS',
      mem: 1152,
      cpus: 1,
      gpus: 0,
      disk: null,
      price: 0.0222222222,
      available: true,
      microservice: false,
      machine_learning: false,
      nice: 0,
      price_id: 'apps.XS',
      memory: {
        unit: 'B',
        value: 1073741824,
        formatted: '1024 MiB',
      },
    },
    buildFlavor: {
      name: 'M',
      mem: 4096,
      cpus: 4,
      gpus: 0,
      disk: null,
      price: 0.1055555556,
      available: true,
      microservice: false,
      machine_learning: false,
      nice: 0,
      price_id: 'apps.M',
      memory: {
        unit: 'B',
        value: 4294967296,
        formatted: '4096 MiB',
      },
    },
  },
  {
    type: 'haskell',
    version: '20230719',
    name: 'Haskell',
    variant: {
      id: '558bab39-508c-4a04-96ca-d1fb4d6a60b4',
      slug: 'haskell',
      name: 'Haskell',
      deployType: 'haskell',
      logo: 'https://assets.clever-cloud.com/logos/haskell.svg',
    },
    description: 'Haskell',
    enabled: true,
    comingSoon: false,
    maxInstances: 40,
    tags: [],
    deployments: [
      'git',
    ],
    flavors: [
      {
        name: 'pico',
        mem: 326,
        cpus: 1,
        gpus: 0,
        disk: null,
        price: 0.0062500000,
        available: true,
        microservice: true,
        machine_learning: false,
        nice: 5,
        price_id: 'apps.pico',
        memory: {
          unit: 'B',
          value: 268435456,
          formatted: '256 MiB',
        },
      },
      {
        name: 'nano',
        mem: 582,
        cpus: 1,
        gpus: 0,
        disk: null,
        price: 0.0083333333,
        available: true,
        microservice: true,
        machine_learning: false,
        nice: 5,
        price_id: 'apps.nano',
        memory: {
          unit: 'B',
          value: 536870912,
          formatted: '512 MiB',
        },
      },
      {
        name: 'XS',
        mem: 1152,
        cpus: 1,
        gpus: 0,
        disk: null,
        price: 0.0222222222,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.XS',
        memory: {
          unit: 'B',
          value: 1073741824,
          formatted: '1024 MiB',
        },
      },
      {
        name: 'S',
        mem: 2048,
        cpus: 2,
        gpus: 0,
        disk: null,
        price: 0.0444444444,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.S',
        memory: {
          unit: 'B',
          value: 2147483648,
          formatted: '2048 MiB',
        },
      },
      {
        name: 'M',
        mem: 4096,
        cpus: 4,
        gpus: 0,
        disk: null,
        price: 0.1055555556,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.M',
        memory: {
          unit: 'B',
          value: 4294967296,
          formatted: '4096 MiB',
        },
      },
      {
        name: 'L',
        mem: 8192,
        cpus: 6,
        gpus: 0,
        disk: null,
        price: 0.2111111111,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.L',
        memory: {
          unit: 'B',
          value: 8589934592,
          formatted: '8192 MiB',
        },
      },
      {
        name: 'XL',
        mem: 16384,
        cpus: 8,
        gpus: 0,
        disk: null,
        price: 0.4222222222,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.XL',
        memory: {
          unit: 'B',
          value: 17179869184,
          formatted: '16384 MiB',
        },
      },
      {
        name: '2XL',
        mem: 24576,
        cpus: 12,
        gpus: 0,
        disk: null,
        price: 0.6666666667,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.2XL',
        memory: {
          unit: 'B',
          value: 25769803776,
          formatted: '24576 MiB',
        },
      },
      {
        name: '3XL',
        mem: 32768,
        cpus: 16,
        gpus: 0,
        disk: null,
        price: 0.8888888889,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.3XL',
        memory: {
          unit: 'B',
          value: 34359738368,
          formatted: '32768 MiB',
        },
      },
    ],
    defaultFlavor: {
      name: 'XS',
      mem: 1152,
      cpus: 1,
      gpus: 0,
      disk: null,
      price: 0.0222222222,
      available: true,
      microservice: false,
      machine_learning: false,
      nice: 0,
      price_id: 'apps.XS',
      memory: {
        unit: 'B',
        value: 1073741824,
        formatted: '1024 MiB',
      },
    },
    buildFlavor: {
      name: 'L',
      mem: 8192,
      cpus: 6,
      gpus: 0,
      disk: null,
      price: 0.2111111111,
      available: true,
      microservice: false,
      machine_learning: false,
      nice: 0,
      price_id: 'apps.L',
      memory: {
        unit: 'B',
        value: 8589934592,
        formatted: '8192 MiB',
      },
    },
  },
  {
    type: 'ruby',
    version: '20230719',
    name: 'Ruby',
    variant: {
      id: '9395c197-fb6d-4b5e-97c6-cc389140ef26',
      slug: 'ruby',
      name: 'Ruby',
      deployType: 'ruby',
      logo: 'https://assets.clever-cloud.com/logos/ruby.svg',
    },
    description: 'ruby',
    enabled: true,
    comingSoon: false,
    maxInstances: 40,
    tags: [
      'ruby',
    ],
    deployments: [
      'git',
    ],
    flavors: [
      {
        name: 'pico',
        mem: 326,
        cpus: 1,
        gpus: 0,
        disk: null,
        price: 0.0062500000,
        available: true,
        microservice: true,
        machine_learning: false,
        nice: 5,
        price_id: 'apps.pico',
        memory: {
          unit: 'B',
          value: 268435456,
          formatted: '256 MiB',
        },
      },
      {
        name: 'nano',
        mem: 582,
        cpus: 1,
        gpus: 0,
        disk: null,
        price: 0.0083333333,
        available: true,
        microservice: true,
        machine_learning: false,
        nice: 5,
        price_id: 'apps.nano',
        memory: {
          unit: 'B',
          value: 536870912,
          formatted: '512 MiB',
        },
      },
      {
        name: 'XS',
        mem: 1152,
        cpus: 1,
        gpus: 0,
        disk: null,
        price: 0.0222222222,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.XS',
        memory: {
          unit: 'B',
          value: 1073741824,
          formatted: '1024 MiB',
        },
      },
      {
        name: 'S',
        mem: 2048,
        cpus: 2,
        gpus: 0,
        disk: null,
        price: 0.0444444444,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.S',
        memory: {
          unit: 'B',
          value: 2147483648,
          formatted: '2048 MiB',
        },
      },
      {
        name: 'M',
        mem: 4096,
        cpus: 4,
        gpus: 0,
        disk: null,
        price: 0.1055555556,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.M',
        memory: {
          unit: 'B',
          value: 4294967296,
          formatted: '4096 MiB',
        },
      },
      {
        name: 'L',
        mem: 8192,
        cpus: 6,
        gpus: 0,
        disk: null,
        price: 0.2111111111,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.L',
        memory: {
          unit: 'B',
          value: 8589934592,
          formatted: '8192 MiB',
        },
      },
      {
        name: 'XL',
        mem: 16384,
        cpus: 8,
        gpus: 0,
        disk: null,
        price: 0.4222222222,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.XL',
        memory: {
          unit: 'B',
          value: 17179869184,
          formatted: '16384 MiB',
        },
      },
      {
        name: '2XL',
        mem: 24576,
        cpus: 12,
        gpus: 0,
        disk: null,
        price: 0.6666666667,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.2XL',
        memory: {
          unit: 'B',
          value: 25769803776,
          formatted: '24576 MiB',
        },
      },
      {
        name: '3XL',
        mem: 32768,
        cpus: 16,
        gpus: 0,
        disk: null,
        price: 0.8888888889,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.3XL',
        memory: {
          unit: 'B',
          value: 34359738368,
          formatted: '32768 MiB',
        },
      },
    ],
    defaultFlavor: {
      name: 'XS',
      mem: 1152,
      cpus: 1,
      gpus: 0,
      disk: null,
      price: 0.0222222222,
      available: true,
      microservice: false,
      machine_learning: false,
      nice: 0,
      price_id: 'apps.XS',
      memory: {
        unit: 'B',
        value: 1073741824,
        formatted: '1024 MiB',
      },
    },
    buildFlavor: {
      name: 'M',
      mem: 4096,
      cpus: 4,
      gpus: 0,
      disk: null,
      price: 0.1055555556,
      available: true,
      microservice: false,
      machine_learning: false,
      nice: 0,
      price_id: 'apps.M',
      memory: {
        unit: 'B',
        value: 4294967296,
        formatted: '4096 MiB',
      },
    },
  },
  {
    type: 'rust',
    version: '20230719',
    name: 'Rust',
    variant: {
      id: '5036303b-a732-489a-9e50-56233eeb1752',
      slug: 'rust',
      name: 'Rust',
      deployType: 'rust',
      logo: 'https://assets.clever-cloud.com/logos/rust.svg',
    },
    description: 'Rust',
    enabled: true,
    comingSoon: false,
    maxInstances: 40,
    tags: [],
    deployments: [
      'git',
    ],
    flavors: [
      {
        name: 'pico',
        mem: 326,
        cpus: 1,
        gpus: 0,
        disk: null,
        price: 0.0062500000,
        available: true,
        microservice: true,
        machine_learning: false,
        nice: 5,
        price_id: 'apps.pico',
        memory: {
          unit: 'B',
          value: 268435456,
          formatted: '256 MiB',
        },
      },
      {
        name: 'nano',
        mem: 582,
        cpus: 1,
        gpus: 0,
        disk: null,
        price: 0.0083333333,
        available: true,
        microservice: true,
        machine_learning: false,
        nice: 5,
        price_id: 'apps.nano',
        memory: {
          unit: 'B',
          value: 536870912,
          formatted: '512 MiB',
        },
      },
      {
        name: 'XS',
        mem: 1152,
        cpus: 1,
        gpus: 0,
        disk: null,
        price: 0.0222222222,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.XS',
        memory: {
          unit: 'B',
          value: 1073741824,
          formatted: '1024 MiB',
        },
      },
      {
        name: 'S',
        mem: 2048,
        cpus: 2,
        gpus: 0,
        disk: null,
        price: 0.0444444444,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.S',
        memory: {
          unit: 'B',
          value: 2147483648,
          formatted: '2048 MiB',
        },
      },
      {
        name: 'M',
        mem: 4096,
        cpus: 4,
        gpus: 0,
        disk: null,
        price: 0.1055555556,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.M',
        memory: {
          unit: 'B',
          value: 4294967296,
          formatted: '4096 MiB',
        },
      },
      {
        name: 'L',
        mem: 8192,
        cpus: 6,
        gpus: 0,
        disk: null,
        price: 0.2111111111,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.L',
        memory: {
          unit: 'B',
          value: 8589934592,
          formatted: '8192 MiB',
        },
      },
      {
        name: 'XL',
        mem: 16384,
        cpus: 8,
        gpus: 0,
        disk: null,
        price: 0.4222222222,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.XL',
        memory: {
          unit: 'B',
          value: 17179869184,
          formatted: '16384 MiB',
        },
      },
      {
        name: '2XL',
        mem: 24576,
        cpus: 12,
        gpus: 0,
        disk: null,
        price: 0.6666666667,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.2XL',
        memory: {
          unit: 'B',
          value: 25769803776,
          formatted: '24576 MiB',
        },
      },
      {
        name: '3XL',
        mem: 32768,
        cpus: 16,
        gpus: 0,
        disk: null,
        price: 0.8888888889,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.3XL',
        memory: {
          unit: 'B',
          value: 34359738368,
          formatted: '32768 MiB',
        },
      },
    ],
    defaultFlavor: {
      name: 'XS',
      mem: 1152,
      cpus: 1,
      gpus: 0,
      disk: null,
      price: 0.0222222222,
      available: true,
      microservice: false,
      machine_learning: false,
      nice: 0,
      price_id: 'apps.XS',
      memory: {
        unit: 'B',
        value: 1073741824,
        formatted: '1024 MiB',
      },
    },
    buildFlavor: {
      name: 'M',
      mem: 4096,
      cpus: 4,
      gpus: 0,
      disk: null,
      price: 0.1055555556,
      available: true,
      microservice: false,
      machine_learning: false,
      nice: 0,
      price_id: 'apps.M',
      memory: {
        unit: 'B',
        value: 4294967296,
        formatted: '4096 MiB',
      },
    },
  },
  {
    type: 'python',
    version: '20230719',
    name: 'Python',
    variant: {
      id: '049c84e1-56a4-4a6a-8940-7ba7e0f57c61',
      slug: 'python',
      name: 'Python',
      deployType: 'python',
      logo: 'https://assets.clever-cloud.com/logos/python.svg',
    },
    description: 'Python scaler type',
    enabled: true,
    comingSoon: false,
    maxInstances: 40,
    tags: [
      'python',
    ],
    deployments: [
      'git',
    ],
    flavors: [
      {
        name: 'pico',
        mem: 326,
        cpus: 1,
        gpus: 0,
        disk: null,
        price: 0.0062500000,
        available: true,
        microservice: true,
        machine_learning: false,
        nice: 5,
        price_id: 'apps.pico',
        memory: {
          unit: 'B',
          value: 268435456,
          formatted: '256 MiB',
        },
      },
      {
        name: 'nano',
        mem: 582,
        cpus: 1,
        gpus: 0,
        disk: null,
        price: 0.0083333333,
        available: true,
        microservice: true,
        machine_learning: false,
        nice: 5,
        price_id: 'apps.nano',
        memory: {
          unit: 'B',
          value: 536870912,
          formatted: '512 MiB',
        },
      },
      {
        name: 'XS',
        mem: 1152,
        cpus: 1,
        gpus: 0,
        disk: null,
        price: 0.0222222222,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.XS',
        memory: {
          unit: 'B',
          value: 1073741824,
          formatted: '1024 MiB',
        },
      },
      {
        name: 'S',
        mem: 2048,
        cpus: 2,
        gpus: 0,
        disk: null,
        price: 0.0444444444,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.S',
        memory: {
          unit: 'B',
          value: 2147483648,
          formatted: '2048 MiB',
        },
      },
      {
        name: 'M',
        mem: 4096,
        cpus: 4,
        gpus: 0,
        disk: null,
        price: 0.1055555556,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.M',
        memory: {
          unit: 'B',
          value: 4294967296,
          formatted: '4096 MiB',
        },
      },
      {
        name: 'L',
        mem: 8192,
        cpus: 6,
        gpus: 0,
        disk: null,
        price: 0.2111111111,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.L',
        memory: {
          unit: 'B',
          value: 8589934592,
          formatted: '8192 MiB',
        },
      },
      {
        name: 'XL',
        mem: 16384,
        cpus: 8,
        gpus: 0,
        disk: null,
        price: 0.4222222222,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.XL',
        memory: {
          unit: 'B',
          value: 17179869184,
          formatted: '16384 MiB',
        },
      },
      {
        name: '2XL',
        mem: 24576,
        cpus: 12,
        gpus: 0,
        disk: null,
        price: 0.6666666667,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.2XL',
        memory: {
          unit: 'B',
          value: 25769803776,
          formatted: '24576 MiB',
        },
      },
      {
        name: '3XL',
        mem: 32768,
        cpus: 16,
        gpus: 0,
        disk: null,
        price: 0.8888888889,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.3XL',
        memory: {
          unit: 'B',
          value: 34359738368,
          formatted: '32768 MiB',
        },
      },
    ],
    defaultFlavor: {
      name: 'XS',
      mem: 1152,
      cpus: 1,
      gpus: 0,
      disk: null,
      price: 0.0222222222,
      available: true,
      microservice: false,
      machine_learning: false,
      nice: 0,
      price_id: 'apps.XS',
      memory: {
        unit: 'B',
        value: 1073741824,
        formatted: '1024 MiB',
      },
    },
    buildFlavor: {
      name: 'S',
      mem: 2048,
      cpus: 2,
      gpus: 0,
      disk: null,
      price: 0.0444444444,
      available: true,
      microservice: false,
      machine_learning: false,
      nice: 0,
      price_id: 'apps.S',
      memory: {
        unit: 'B',
        value: 2147483648,
        formatted: '2048 MiB',
      },
    },
  },
  {
    type: 'node',
    version: '20230719',
    name: 'Meteor.js',
    variant: {
      id: '4afcf49b-6819-4bba-a062-ab2c11278b9d',
      slug: 'meteor',
      name: 'Meteor.js',
      deployType: 'node',
      logo: 'https://assets.clever-cloud.com/logos/meteor.svg',
    },
    description: 'node',
    enabled: true,
    comingSoon: false,
    maxInstances: 40,
    tags: [
      'javascript',
      'node',
    ],
    deployments: [
      'git',
    ],
    flavors: [
      {
        name: 'pico',
        mem: 326,
        cpus: 1,
        gpus: 0,
        disk: null,
        price: 0.0062500000,
        available: true,
        microservice: true,
        machine_learning: false,
        nice: 5,
        price_id: 'apps.pico',
        memory: {
          unit: 'B',
          value: 268435456,
          formatted: '256 MiB',
        },
      },
      {
        name: 'nano',
        mem: 582,
        cpus: 1,
        gpus: 0,
        disk: null,
        price: 0.0083333333,
        available: true,
        microservice: true,
        machine_learning: false,
        nice: 5,
        price_id: 'apps.nano',
        memory: {
          unit: 'B',
          value: 536870912,
          formatted: '512 MiB',
        },
      },
      {
        name: 'XS',
        mem: 1152,
        cpus: 1,
        gpus: 0,
        disk: null,
        price: 0.0222222222,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.XS',
        memory: {
          unit: 'B',
          value: 1073741824,
          formatted: '1024 MiB',
        },
      },
      {
        name: 'S',
        mem: 2048,
        cpus: 2,
        gpus: 0,
        disk: null,
        price: 0.0444444444,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.S',
        memory: {
          unit: 'B',
          value: 2147483648,
          formatted: '2048 MiB',
        },
      },
      {
        name: 'M',
        mem: 4096,
        cpus: 4,
        gpus: 0,
        disk: null,
        price: 0.1055555556,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.M',
        memory: {
          unit: 'B',
          value: 4294967296,
          formatted: '4096 MiB',
        },
      },
      {
        name: 'L',
        mem: 8192,
        cpus: 6,
        gpus: 0,
        disk: null,
        price: 0.2111111111,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.L',
        memory: {
          unit: 'B',
          value: 8589934592,
          formatted: '8192 MiB',
        },
      },
      {
        name: 'XL',
        mem: 16384,
        cpus: 8,
        gpus: 0,
        disk: null,
        price: 0.4222222222,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.XL',
        memory: {
          unit: 'B',
          value: 17179869184,
          formatted: '16384 MiB',
        },
      },
      {
        name: '2XL',
        mem: 24576,
        cpus: 12,
        gpus: 0,
        disk: null,
        price: 0.6666666667,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.2XL',
        memory: {
          unit: 'B',
          value: 25769803776,
          formatted: '24576 MiB',
        },
      },
      {
        name: '3XL',
        mem: 32768,
        cpus: 16,
        gpus: 0,
        disk: null,
        price: 0.8888888889,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.3XL',
        memory: {
          unit: 'B',
          value: 34359738368,
          formatted: '32768 MiB',
        },
      },
    ],
    defaultFlavor: {
      name: 'XS',
      mem: 1152,
      cpus: 1,
      gpus: 0,
      disk: null,
      price: 0.0222222222,
      available: true,
      microservice: false,
      machine_learning: false,
      nice: 0,
      price_id: 'apps.XS',
      memory: {
        unit: 'B',
        value: 1073741824,
        formatted: '1024 MiB',
      },
    },
    buildFlavor: {
      name: 'S',
      mem: 2048,
      cpus: 2,
      gpus: 0,
      disk: null,
      price: 0.0444444444,
      available: true,
      microservice: false,
      machine_learning: false,
      nice: 0,
      price_id: 'apps.S',
      memory: {
        unit: 'B',
        value: 2147483648,
        formatted: '2048 MiB',
      },
    },
  },
  {
    type: 'node',
    version: '20230719',
    name: 'Node',
    variant: {
      id: '395103fb-d6e2-4fdd-93bc-bc99146f1ea2',
      slug: 'node',
      name: 'Node',
      deployType: 'node',
      logo: 'https://assets.clever-cloud.com/logos/nodejs.svg',
    },
    description: 'node',
    enabled: true,
    comingSoon: false,
    maxInstances: 40,
    tags: [
      'javascript',
      'node',
    ],
    deployments: [
      'git',
    ],
    flavors: [
      {
        name: 'pico',
        mem: 326,
        cpus: 1,
        gpus: 0,
        disk: null,
        price: 0.0062500000,
        available: true,
        microservice: true,
        machine_learning: false,
        nice: 5,
        price_id: 'apps.pico',
        memory: {
          unit: 'B',
          value: 268435456,
          formatted: '256 MiB',
        },
      },
      {
        name: 'nano',
        mem: 582,
        cpus: 1,
        gpus: 0,
        disk: null,
        price: 0.0083333333,
        available: true,
        microservice: true,
        machine_learning: false,
        nice: 5,
        price_id: 'apps.nano',
        memory: {
          unit: 'B',
          value: 536870912,
          formatted: '512 MiB',
        },
      },
      {
        name: 'XS',
        mem: 1152,
        cpus: 1,
        gpus: 0,
        disk: null,
        price: 0.0222222222,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.XS',
        memory: {
          unit: 'B',
          value: 1073741824,
          formatted: '1024 MiB',
        },
      },
      {
        name: 'S',
        mem: 2048,
        cpus: 2,
        gpus: 0,
        disk: null,
        price: 0.0444444444,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.S',
        memory: {
          unit: 'B',
          value: 2147483648,
          formatted: '2048 MiB',
        },
      },
      {
        name: 'M',
        mem: 4096,
        cpus: 4,
        gpus: 0,
        disk: null,
        price: 0.1055555556,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.M',
        memory: {
          unit: 'B',
          value: 4294967296,
          formatted: '4096 MiB',
        },
      },
      {
        name: 'L',
        mem: 8192,
        cpus: 6,
        gpus: 0,
        disk: null,
        price: 0.2111111111,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.L',
        memory: {
          unit: 'B',
          value: 8589934592,
          formatted: '8192 MiB',
        },
      },
      {
        name: 'XL',
        mem: 16384,
        cpus: 8,
        gpus: 0,
        disk: null,
        price: 0.4222222222,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.XL',
        memory: {
          unit: 'B',
          value: 17179869184,
          formatted: '16384 MiB',
        },
      },
      {
        name: '2XL',
        mem: 24576,
        cpus: 12,
        gpus: 0,
        disk: null,
        price: 0.6666666667,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.2XL',
        memory: {
          unit: 'B',
          value: 25769803776,
          formatted: '24576 MiB',
        },
      },
      {
        name: '3XL',
        mem: 32768,
        cpus: 16,
        gpus: 0,
        disk: null,
        price: 0.8888888889,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.3XL',
        memory: {
          unit: 'B',
          value: 34359738368,
          formatted: '32768 MiB',
        },
      },
    ],
    defaultFlavor: {
      name: 'XS',
      mem: 1152,
      cpus: 1,
      gpus: 0,
      disk: null,
      price: 0.0222222222,
      available: true,
      microservice: false,
      machine_learning: false,
      nice: 0,
      price_id: 'apps.XS',
      memory: {
        unit: 'B',
        value: 1073741824,
        formatted: '1024 MiB',
      },
    },
    buildFlavor: {
      name: 'S',
      mem: 2048,
      cpus: 2,
      gpus: 0,
      disk: null,
      price: 0.0444444444,
      available: true,
      microservice: false,
      machine_learning: false,
      nice: 0,
      price_id: 'apps.S',
      memory: {
        unit: 'B',
        value: 2147483648,
        formatted: '2048 MiB',
      },
    },
  },
  {
    type: 'go',
    version: '20231018',
    name: 'Go',
    variant: {
      id: 'b7e506a9-241e-49b9-85d4-df74d85e0178',
      slug: 'go',
      name: 'Go',
      deployType: 'go',
      logo: 'https://assets.clever-cloud.com/logos/go.svg',
    },
    description: 'go',
    enabled: true,
    comingSoon: false,
    maxInstances: 40,
    tags: [],
    deployments: [
      'git',
    ],
    flavors: [
      {
        name: 'pico',
        mem: 326,
        cpus: 1,
        gpus: 0,
        disk: null,
        price: 0.0062500000,
        available: true,
        microservice: true,
        machine_learning: false,
        nice: 5,
        price_id: 'apps.pico',
        memory: {
          unit: 'B',
          value: 268435456,
          formatted: '256 MiB',
        },
      },
      {
        name: 'nano',
        mem: 582,
        cpus: 1,
        gpus: 0,
        disk: null,
        price: 0.0083333333,
        available: true,
        microservice: true,
        machine_learning: false,
        nice: 5,
        price_id: 'apps.nano',
        memory: {
          unit: 'B',
          value: 536870912,
          formatted: '512 MiB',
        },
      },
      {
        name: 'XS',
        mem: 1152,
        cpus: 1,
        gpus: 0,
        disk: null,
        price: 0.0222222222,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.XS',
        memory: {
          unit: 'B',
          value: 1073741824,
          formatted: '1024 MiB',
        },
      },
      {
        name: 'S',
        mem: 2048,
        cpus: 2,
        gpus: 0,
        disk: null,
        price: 0.0444444444,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.S',
        memory: {
          unit: 'B',
          value: 2147483648,
          formatted: '2048 MiB',
        },
      },
      {
        name: 'M',
        mem: 4096,
        cpus: 4,
        gpus: 0,
        disk: null,
        price: 0.1055555556,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.M',
        memory: {
          unit: 'B',
          value: 4294967296,
          formatted: '4096 MiB',
        },
      },
      {
        name: 'L',
        mem: 8192,
        cpus: 6,
        gpus: 0,
        disk: null,
        price: 0.2111111111,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.L',
        memory: {
          unit: 'B',
          value: 8589934592,
          formatted: '8192 MiB',
        },
      },
      {
        name: 'XL',
        mem: 16384,
        cpus: 8,
        gpus: 0,
        disk: null,
        price: 0.4222222222,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.XL',
        memory: {
          unit: 'B',
          value: 17179869184,
          formatted: '16384 MiB',
        },
      },
      {
        name: '2XL',
        mem: 24576,
        cpus: 12,
        gpus: 0,
        disk: null,
        price: 0.6666666667,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.2XL',
        memory: {
          unit: 'B',
          value: 25769803776,
          formatted: '24576 MiB',
        },
      },
      {
        name: '3XL',
        mem: 32768,
        cpus: 16,
        gpus: 0,
        disk: null,
        price: 0.8888888889,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.3XL',
        memory: {
          unit: 'B',
          value: 34359738368,
          formatted: '32768 MiB',
        },
      },
    ],
    defaultFlavor: {
      name: 'XS',
      mem: 1152,
      cpus: 1,
      gpus: 0,
      disk: null,
      price: 0.0222222222,
      available: true,
      microservice: false,
      machine_learning: false,
      nice: 0,
      price_id: 'apps.XS',
      memory: {
        unit: 'B',
        value: 1073741824,
        formatted: '1024 MiB',
      },
    },
    buildFlavor: {
      name: 'S',
      mem: 2048,
      cpus: 2,
      gpus: 0,
      disk: null,
      price: 0.0444444444,
      available: true,
      microservice: false,
      machine_learning: false,
      nice: 0,
      price_id: 'apps.S',
      memory: {
        unit: 'B',
        value: 2147483648,
        formatted: '2048 MiB',
      },
    },
  },
  {
    type: 'php',
    version: '20231110',
    name: 'PHP',
    variant: {
      id: 'ca6c9c85-63f8-4075-b136-583d3f581a52',
      slug: 'php',
      name: 'PHP',
      deployType: 'php',
      logo: 'https://assets.clever-cloud.com/logos/php.svg',
    },
    description: 'Multi PHP',
    enabled: true,
    comingSoon: false,
    maxInstances: 40,
    tags: [],
    deployments: [
      'ftp',
      'git',
    ],
    flavors: [
      {
        name: 'nano',
        mem: 582,
        cpus: 1,
        gpus: 0,
        disk: null,
        price: 0.0083333333,
        available: true,
        microservice: true,
        machine_learning: false,
        nice: 5,
        price_id: 'apps.nano',
        memory: {
          unit: 'B',
          value: 536870912,
          formatted: '512 MiB',
        },
      },
      {
        name: 'XS',
        mem: 1152,
        cpus: 1,
        gpus: 0,
        disk: null,
        price: 0.0222222222,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.XS',
        memory: {
          unit: 'B',
          value: 1073741824,
          formatted: '1024 MiB',
        },
      },
      {
        name: 'S',
        mem: 2048,
        cpus: 2,
        gpus: 0,
        disk: null,
        price: 0.0444444444,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.S',
        memory: {
          unit: 'B',
          value: 2147483648,
          formatted: '2048 MiB',
        },
      },
      {
        name: 'M',
        mem: 4096,
        cpus: 4,
        gpus: 0,
        disk: null,
        price: 0.1055555556,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.M',
        memory: {
          unit: 'B',
          value: 4294967296,
          formatted: '4096 MiB',
        },
      },
      {
        name: 'L',
        mem: 8192,
        cpus: 6,
        gpus: 0,
        disk: null,
        price: 0.2111111111,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.L',
        memory: {
          unit: 'B',
          value: 8589934592,
          formatted: '8192 MiB',
        },
      },
      {
        name: 'XL',
        mem: 16384,
        cpus: 8,
        gpus: 0,
        disk: null,
        price: 0.4222222222,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.XL',
        memory: {
          unit: 'B',
          value: 17179869184,
          formatted: '16384 MiB',
        },
      },
      {
        name: '2XL',
        mem: 24576,
        cpus: 12,
        gpus: 0,
        disk: null,
        price: 0.6666666667,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.2XL',
        memory: {
          unit: 'B',
          value: 25769803776,
          formatted: '24576 MiB',
        },
      },
      {
        name: '3XL',
        mem: 32768,
        cpus: 16,
        gpus: 0,
        disk: null,
        price: 0.8888888889,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.3XL',
        memory: {
          unit: 'B',
          value: 34359738368,
          formatted: '32768 MiB',
        },
      },
    ],
    defaultFlavor: {
      name: 'XS',
      mem: 1152,
      cpus: 1,
      gpus: 0,
      disk: null,
      price: 0.0222222222,
      available: true,
      microservice: false,
      machine_learning: false,
      nice: 0,
      price_id: 'apps.XS',
      memory: {
        unit: 'B',
        value: 1073741824,
        formatted: '1024 MiB',
      },
    },
    buildFlavor: {
      name: 'M',
      mem: 4096,
      cpus: 4,
      gpus: 0,
      disk: null,
      price: 0.1055555556,
      available: true,
      microservice: false,
      machine_learning: false,
      nice: 0,
      price_id: 'apps.M',
      memory: {
        unit: 'B',
        value: 4294967296,
        formatted: '4096 MiB',
      },
    },
  },
  {
    type: 'php',
    version: '20231110',
    name: 'Static',
    variant: {
      id: '3b8cc37b-b874-4169-b64e-7eace63dfb7b',
      slug: 'static-apache',
      name: 'Static',
      deployType: 'php',
      logo: 'https://assets.clever-cloud.com/logos/apache.svg',
    },
    description: 'Multi PHP',
    enabled: true,
    comingSoon: false,
    maxInstances: 40,
    tags: [],
    deployments: [
      'ftp',
      'git',
    ],
    flavors: [
      {
        name: 'nano',
        mem: 582,
        cpus: 1,
        gpus: 0,
        disk: null,
        price: 0.0083333333,
        available: true,
        microservice: true,
        machine_learning: false,
        nice: 5,
        price_id: 'apps.nano',
        memory: {
          unit: 'B',
          value: 536870912,
          formatted: '512 MiB',
        },
      },
      {
        name: 'XS',
        mem: 1152,
        cpus: 1,
        gpus: 0,
        disk: null,
        price: 0.0222222222,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.XS',
        memory: {
          unit: 'B',
          value: 1073741824,
          formatted: '1024 MiB',
        },
      },
      {
        name: 'S',
        mem: 2048,
        cpus: 2,
        gpus: 0,
        disk: null,
        price: 0.0444444444,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.S',
        memory: {
          unit: 'B',
          value: 2147483648,
          formatted: '2048 MiB',
        },
      },
      {
        name: 'M',
        mem: 4096,
        cpus: 4,
        gpus: 0,
        disk: null,
        price: 0.1055555556,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.M',
        memory: {
          unit: 'B',
          value: 4294967296,
          formatted: '4096 MiB',
        },
      },
      {
        name: 'L',
        mem: 8192,
        cpus: 6,
        gpus: 0,
        disk: null,
        price: 0.2111111111,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.L',
        memory: {
          unit: 'B',
          value: 8589934592,
          formatted: '8192 MiB',
        },
      },
      {
        name: 'XL',
        mem: 16384,
        cpus: 8,
        gpus: 0,
        disk: null,
        price: 0.4222222222,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.XL',
        memory: {
          unit: 'B',
          value: 17179869184,
          formatted: '16384 MiB',
        },
      },
      {
        name: '2XL',
        mem: 24576,
        cpus: 12,
        gpus: 0,
        disk: null,
        price: 0.6666666667,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.2XL',
        memory: {
          unit: 'B',
          value: 25769803776,
          formatted: '24576 MiB',
        },
      },
      {
        name: '3XL',
        mem: 32768,
        cpus: 16,
        gpus: 0,
        disk: null,
        price: 0.8888888889,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.3XL',
        memory: {
          unit: 'B',
          value: 34359738368,
          formatted: '32768 MiB',
        },
      },
    ],
    defaultFlavor: {
      name: 'XS',
      mem: 1152,
      cpus: 1,
      gpus: 0,
      disk: null,
      price: 0.0222222222,
      available: true,
      microservice: false,
      machine_learning: false,
      nice: 0,
      price_id: 'apps.XS',
      memory: {
        unit: 'B',
        value: 1073741824,
        formatted: '1024 MiB',
      },
    },
    buildFlavor: {
      name: 'M',
      mem: 4096,
      cpus: 4,
      gpus: 0,
      disk: null,
      price: 0.1055555556,
      available: true,
      microservice: false,
      machine_learning: false,
      nice: 0,
      price_id: 'apps.M',
      memory: {
        unit: 'B',
        value: 4294967296,
        formatted: '4096 MiB',
      },
    },
  },
  {
    type: 'java',
    version: '20231110',
    name: 'Java + Play! 1',
    variant: {
      id: '3112d076-1e33-4f06-9efe-9a766619a2ba',
      slug: 'play1',
      name: 'Java + Play! 1',
      deployType: 'java',
      logo: 'https://assets.clever-cloud.com/logos/play1.svg',
    },
    description: 'java',
    enabled: true,
    comingSoon: false,
    maxInstances: 40,
    tags: [
      'gradle',
      'jar',
      'java',
      'jvm',
      'maven',
      'mvn',
      'play',
      'sbt',
      'war',
    ],
    deployments: [
      'git',
    ],
    flavors: [
      {
        name: 'pico',
        mem: 326,
        cpus: 1,
        gpus: 0,
        disk: null,
        price: 0.0062500000,
        available: true,
        microservice: true,
        machine_learning: false,
        nice: 5,
        price_id: 'apps.pico',
        memory: {
          unit: 'B',
          value: 268435456,
          formatted: '256 MiB',
        },
      },
      {
        name: 'nano',
        mem: 582,
        cpus: 1,
        gpus: 0,
        disk: null,
        price: 0.0083333333,
        available: true,
        microservice: true,
        machine_learning: false,
        nice: 5,
        price_id: 'apps.nano',
        memory: {
          unit: 'B',
          value: 536870912,
          formatted: '512 MiB',
        },
      },
      {
        name: 'XS',
        mem: 1152,
        cpus: 1,
        gpus: 0,
        disk: null,
        price: 0.0222222222,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.XS',
        memory: {
          unit: 'B',
          value: 1073741824,
          formatted: '1024 MiB',
        },
      },
      {
        name: 'S',
        mem: 2048,
        cpus: 2,
        gpus: 0,
        disk: null,
        price: 0.0444444444,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.S',
        memory: {
          unit: 'B',
          value: 2147483648,
          formatted: '2048 MiB',
        },
      },
      {
        name: 'M',
        mem: 4096,
        cpus: 4,
        gpus: 0,
        disk: null,
        price: 0.1055555556,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.M',
        memory: {
          unit: 'B',
          value: 4294967296,
          formatted: '4096 MiB',
        },
      },
      {
        name: 'L',
        mem: 8192,
        cpus: 6,
        gpus: 0,
        disk: null,
        price: 0.2111111111,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.L',
        memory: {
          unit: 'B',
          value: 8589934592,
          formatted: '8192 MiB',
        },
      },
      {
        name: 'XL',
        mem: 16384,
        cpus: 8,
        gpus: 0,
        disk: null,
        price: 0.4222222222,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.XL',
        memory: {
          unit: 'B',
          value: 17179869184,
          formatted: '16384 MiB',
        },
      },
      {
        name: '2XL',
        mem: 24576,
        cpus: 12,
        gpus: 0,
        disk: null,
        price: 0.6666666667,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.2XL',
        memory: {
          unit: 'B',
          value: 25769803776,
          formatted: '24576 MiB',
        },
      },
      {
        name: '3XL',
        mem: 32768,
        cpus: 16,
        gpus: 0,
        disk: null,
        price: 0.8888888889,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.3XL',
        memory: {
          unit: 'B',
          value: 34359738368,
          formatted: '32768 MiB',
        },
      },
    ],
    defaultFlavor: {
      name: 'XS',
      mem: 1152,
      cpus: 1,
      gpus: 0,
      disk: null,
      price: 0.0222222222,
      available: true,
      microservice: false,
      machine_learning: false,
      nice: 0,
      price_id: 'apps.XS',
      memory: {
        unit: 'B',
        value: 1073741824,
        formatted: '1024 MiB',
      },
    },
    buildFlavor: {
      name: 'M',
      mem: 4096,
      cpus: 4,
      gpus: 0,
      disk: null,
      price: 0.1055555556,
      available: true,
      microservice: false,
      machine_learning: false,
      nice: 0,
      price_id: 'apps.M',
      memory: {
        unit: 'B',
        value: 4294967296,
        formatted: '4096 MiB',
      },
    },
  },
  {
    type: 'java',
    version: '20231110',
    name: 'Java or Scala + Play! 2',
    variant: {
      id: 'ea6625a2-3ff6-4662-b724-280fc2f400b9',
      slug: 'play2',
      name: 'Java or Scala + Play! 2',
      deployType: 'java',
      logo: 'https://assets.clever-cloud.com/logos/play2.svg',
    },
    description: 'java',
    enabled: true,
    comingSoon: false,
    maxInstances: 40,
    tags: [
      'gradle',
      'jar',
      'java',
      'jvm',
      'maven',
      'mvn',
      'play',
      'sbt',
      'war',
    ],
    deployments: [
      'git',
    ],
    flavors: [
      {
        name: 'pico',
        mem: 326,
        cpus: 1,
        gpus: 0,
        disk: null,
        price: 0.0062500000,
        available: true,
        microservice: true,
        machine_learning: false,
        nice: 5,
        price_id: 'apps.pico',
        memory: {
          unit: 'B',
          value: 268435456,
          formatted: '256 MiB',
        },
      },
      {
        name: 'nano',
        mem: 582,
        cpus: 1,
        gpus: 0,
        disk: null,
        price: 0.0083333333,
        available: true,
        microservice: true,
        machine_learning: false,
        nice: 5,
        price_id: 'apps.nano',
        memory: {
          unit: 'B',
          value: 536870912,
          formatted: '512 MiB',
        },
      },
      {
        name: 'XS',
        mem: 1152,
        cpus: 1,
        gpus: 0,
        disk: null,
        price: 0.0222222222,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.XS',
        memory: {
          unit: 'B',
          value: 1073741824,
          formatted: '1024 MiB',
        },
      },
      {
        name: 'S',
        mem: 2048,
        cpus: 2,
        gpus: 0,
        disk: null,
        price: 0.0444444444,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.S',
        memory: {
          unit: 'B',
          value: 2147483648,
          formatted: '2048 MiB',
        },
      },
      {
        name: 'M',
        mem: 4096,
        cpus: 4,
        gpus: 0,
        disk: null,
        price: 0.1055555556,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.M',
        memory: {
          unit: 'B',
          value: 4294967296,
          formatted: '4096 MiB',
        },
      },
      {
        name: 'L',
        mem: 8192,
        cpus: 6,
        gpus: 0,
        disk: null,
        price: 0.2111111111,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.L',
        memory: {
          unit: 'B',
          value: 8589934592,
          formatted: '8192 MiB',
        },
      },
      {
        name: 'XL',
        mem: 16384,
        cpus: 8,
        gpus: 0,
        disk: null,
        price: 0.4222222222,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.XL',
        memory: {
          unit: 'B',
          value: 17179869184,
          formatted: '16384 MiB',
        },
      },
      {
        name: '2XL',
        mem: 24576,
        cpus: 12,
        gpus: 0,
        disk: null,
        price: 0.6666666667,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.2XL',
        memory: {
          unit: 'B',
          value: 25769803776,
          formatted: '24576 MiB',
        },
      },
      {
        name: '3XL',
        mem: 32768,
        cpus: 16,
        gpus: 0,
        disk: null,
        price: 0.8888888889,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.3XL',
        memory: {
          unit: 'B',
          value: 34359738368,
          formatted: '32768 MiB',
        },
      },
    ],
    defaultFlavor: {
      name: 'XS',
      mem: 1152,
      cpus: 1,
      gpus: 0,
      disk: null,
      price: 0.0222222222,
      available: true,
      microservice: false,
      machine_learning: false,
      nice: 0,
      price_id: 'apps.XS',
      memory: {
        unit: 'B',
        value: 1073741824,
        formatted: '1024 MiB',
      },
    },
    buildFlavor: {
      name: 'M',
      mem: 4096,
      cpus: 4,
      gpus: 0,
      disk: null,
      price: 0.1055555556,
      available: true,
      microservice: false,
      machine_learning: false,
      nice: 0,
      price_id: 'apps.M',
      memory: {
        unit: 'B',
        value: 4294967296,
        formatted: '4096 MiB',
      },
    },
  },
  {
    type: 'java',
    version: '20231110',
    name: 'Java or Groovy + Gradle',
    variant: {
      id: '5163834d-b343-4006-bfdb-ece9d30fbb51',
      slug: 'gradle',
      name: 'Java or Groovy + Gradle',
      deployType: 'java',
      logo: 'https://assets.clever-cloud.com/logos/gradle.svg',
    },
    description: 'java',
    enabled: true,
    comingSoon: false,
    maxInstances: 40,
    tags: [
      'gradle',
      'jar',
      'java',
      'jvm',
      'maven',
      'mvn',
      'play',
      'sbt',
      'war',
    ],
    deployments: [
      'git',
    ],
    flavors: [
      {
        name: 'pico',
        mem: 326,
        cpus: 1,
        gpus: 0,
        disk: null,
        price: 0.0062500000,
        available: true,
        microservice: true,
        machine_learning: false,
        nice: 5,
        price_id: 'apps.pico',
        memory: {
          unit: 'B',
          value: 268435456,
          formatted: '256 MiB',
        },
      },
      {
        name: 'nano',
        mem: 582,
        cpus: 1,
        gpus: 0,
        disk: null,
        price: 0.0083333333,
        available: true,
        microservice: true,
        machine_learning: false,
        nice: 5,
        price_id: 'apps.nano',
        memory: {
          unit: 'B',
          value: 536870912,
          formatted: '512 MiB',
        },
      },
      {
        name: 'XS',
        mem: 1152,
        cpus: 1,
        gpus: 0,
        disk: null,
        price: 0.0222222222,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.XS',
        memory: {
          unit: 'B',
          value: 1073741824,
          formatted: '1024 MiB',
        },
      },
      {
        name: 'S',
        mem: 2048,
        cpus: 2,
        gpus: 0,
        disk: null,
        price: 0.0444444444,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.S',
        memory: {
          unit: 'B',
          value: 2147483648,
          formatted: '2048 MiB',
        },
      },
      {
        name: 'M',
        mem: 4096,
        cpus: 4,
        gpus: 0,
        disk: null,
        price: 0.1055555556,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.M',
        memory: {
          unit: 'B',
          value: 4294967296,
          formatted: '4096 MiB',
        },
      },
      {
        name: 'L',
        mem: 8192,
        cpus: 6,
        gpus: 0,
        disk: null,
        price: 0.2111111111,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.L',
        memory: {
          unit: 'B',
          value: 8589934592,
          formatted: '8192 MiB',
        },
      },
      {
        name: 'XL',
        mem: 16384,
        cpus: 8,
        gpus: 0,
        disk: null,
        price: 0.4222222222,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.XL',
        memory: {
          unit: 'B',
          value: 17179869184,
          formatted: '16384 MiB',
        },
      },
      {
        name: '2XL',
        mem: 24576,
        cpus: 12,
        gpus: 0,
        disk: null,
        price: 0.6666666667,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.2XL',
        memory: {
          unit: 'B',
          value: 25769803776,
          formatted: '24576 MiB',
        },
      },
      {
        name: '3XL',
        mem: 32768,
        cpus: 16,
        gpus: 0,
        disk: null,
        price: 0.8888888889,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.3XL',
        memory: {
          unit: 'B',
          value: 34359738368,
          formatted: '32768 MiB',
        },
      },
    ],
    defaultFlavor: {
      name: 'XS',
      mem: 1152,
      cpus: 1,
      gpus: 0,
      disk: null,
      price: 0.0222222222,
      available: true,
      microservice: false,
      machine_learning: false,
      nice: 0,
      price_id: 'apps.XS',
      memory: {
        unit: 'B',
        value: 1073741824,
        formatted: '1024 MiB',
      },
    },
    buildFlavor: {
      name: 'M',
      mem: 4096,
      cpus: 4,
      gpus: 0,
      disk: null,
      price: 0.1055555556,
      available: true,
      microservice: false,
      machine_learning: false,
      nice: 0,
      price_id: 'apps.M',
      memory: {
        unit: 'B',
        value: 4294967296,
        formatted: '4096 MiB',
      },
    },
  },
  {
    type: 'java',
    version: '20231110',
    name: 'Java + JAR',
    variant: {
      id: '879bf2c4-54b2-4b84-83f6-704d90c08062',
      slug: 'jar',
      name: 'Java + JAR',
      deployType: 'java',
      logo: 'https://assets.clever-cloud.com/logos/java-jar.svg',
    },
    description: 'java',
    enabled: true,
    comingSoon: false,
    maxInstances: 40,
    tags: [
      'gradle',
      'jar',
      'java',
      'jvm',
      'maven',
      'mvn',
      'play',
      'sbt',
      'war',
    ],
    deployments: [
      'git',
    ],
    flavors: [
      {
        name: 'pico',
        mem: 326,
        cpus: 1,
        gpus: 0,
        disk: null,
        price: 0.0062500000,
        available: true,
        microservice: true,
        machine_learning: false,
        nice: 5,
        price_id: 'apps.pico',
        memory: {
          unit: 'B',
          value: 268435456,
          formatted: '256 MiB',
        },
      },
      {
        name: 'nano',
        mem: 582,
        cpus: 1,
        gpus: 0,
        disk: null,
        price: 0.0083333333,
        available: true,
        microservice: true,
        machine_learning: false,
        nice: 5,
        price_id: 'apps.nano',
        memory: {
          unit: 'B',
          value: 536870912,
          formatted: '512 MiB',
        },
      },
      {
        name: 'XS',
        mem: 1152,
        cpus: 1,
        gpus: 0,
        disk: null,
        price: 0.0222222222,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.XS',
        memory: {
          unit: 'B',
          value: 1073741824,
          formatted: '1024 MiB',
        },
      },
      {
        name: 'S',
        mem: 2048,
        cpus: 2,
        gpus: 0,
        disk: null,
        price: 0.0444444444,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.S',
        memory: {
          unit: 'B',
          value: 2147483648,
          formatted: '2048 MiB',
        },
      },
      {
        name: 'M',
        mem: 4096,
        cpus: 4,
        gpus: 0,
        disk: null,
        price: 0.1055555556,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.M',
        memory: {
          unit: 'B',
          value: 4294967296,
          formatted: '4096 MiB',
        },
      },
      {
        name: 'L',
        mem: 8192,
        cpus: 6,
        gpus: 0,
        disk: null,
        price: 0.2111111111,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.L',
        memory: {
          unit: 'B',
          value: 8589934592,
          formatted: '8192 MiB',
        },
      },
      {
        name: 'XL',
        mem: 16384,
        cpus: 8,
        gpus: 0,
        disk: null,
        price: 0.4222222222,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.XL',
        memory: {
          unit: 'B',
          value: 17179869184,
          formatted: '16384 MiB',
        },
      },
      {
        name: '2XL',
        mem: 24576,
        cpus: 12,
        gpus: 0,
        disk: null,
        price: 0.6666666667,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.2XL',
        memory: {
          unit: 'B',
          value: 25769803776,
          formatted: '24576 MiB',
        },
      },
      {
        name: '3XL',
        mem: 32768,
        cpus: 16,
        gpus: 0,
        disk: null,
        price: 0.8888888889,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.3XL',
        memory: {
          unit: 'B',
          value: 34359738368,
          formatted: '32768 MiB',
        },
      },
    ],
    defaultFlavor: {
      name: 'XS',
      mem: 1152,
      cpus: 1,
      gpus: 0,
      disk: null,
      price: 0.0222222222,
      available: true,
      microservice: false,
      machine_learning: false,
      nice: 0,
      price_id: 'apps.XS',
      memory: {
        unit: 'B',
        value: 1073741824,
        formatted: '1024 MiB',
      },
    },
    buildFlavor: {
      name: 'M',
      mem: 4096,
      cpus: 4,
      gpus: 0,
      disk: null,
      price: 0.1055555556,
      available: true,
      microservice: false,
      machine_learning: false,
      nice: 0,
      price_id: 'apps.M',
      memory: {
        unit: 'B',
        value: 4294967296,
        formatted: '4096 MiB',
      },
    },
  },
  {
    type: 'java',
    version: '20231110',
    name: 'Java + Maven',
    variant: {
      id: 'af524b51-b5a8-4b7f-bd60-d80fa3925b34',
      slug: 'maven',
      name: 'Java + Maven',
      deployType: 'java',
      logo: 'https://assets.clever-cloud.com/logos/maven.svg',
    },
    description: 'java',
    enabled: true,
    comingSoon: false,
    maxInstances: 40,
    tags: [
      'gradle',
      'jar',
      'java',
      'jvm',
      'maven',
      'mvn',
      'play',
      'sbt',
      'war',
    ],
    deployments: [
      'git',
    ],
    flavors: [
      {
        name: 'pico',
        mem: 326,
        cpus: 1,
        gpus: 0,
        disk: null,
        price: 0.0062500000,
        available: true,
        microservice: true,
        machine_learning: false,
        nice: 5,
        price_id: 'apps.pico',
        memory: {
          unit: 'B',
          value: 268435456,
          formatted: '256 MiB',
        },
      },
      {
        name: 'nano',
        mem: 582,
        cpus: 1,
        gpus: 0,
        disk: null,
        price: 0.0083333333,
        available: true,
        microservice: true,
        machine_learning: false,
        nice: 5,
        price_id: 'apps.nano',
        memory: {
          unit: 'B',
          value: 536870912,
          formatted: '512 MiB',
        },
      },
      {
        name: 'XS',
        mem: 1152,
        cpus: 1,
        gpus: 0,
        disk: null,
        price: 0.0222222222,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.XS',
        memory: {
          unit: 'B',
          value: 1073741824,
          formatted: '1024 MiB',
        },
      },
      {
        name: 'S',
        mem: 2048,
        cpus: 2,
        gpus: 0,
        disk: null,
        price: 0.0444444444,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.S',
        memory: {
          unit: 'B',
          value: 2147483648,
          formatted: '2048 MiB',
        },
      },
      {
        name: 'M',
        mem: 4096,
        cpus: 4,
        gpus: 0,
        disk: null,
        price: 0.1055555556,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.M',
        memory: {
          unit: 'B',
          value: 4294967296,
          formatted: '4096 MiB',
        },
      },
      {
        name: 'L',
        mem: 8192,
        cpus: 6,
        gpus: 0,
        disk: null,
        price: 0.2111111111,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.L',
        memory: {
          unit: 'B',
          value: 8589934592,
          formatted: '8192 MiB',
        },
      },
      {
        name: 'XL',
        mem: 16384,
        cpus: 8,
        gpus: 0,
        disk: null,
        price: 0.4222222222,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.XL',
        memory: {
          unit: 'B',
          value: 17179869184,
          formatted: '16384 MiB',
        },
      },
      {
        name: '2XL',
        mem: 24576,
        cpus: 12,
        gpus: 0,
        disk: null,
        price: 0.6666666667,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.2XL',
        memory: {
          unit: 'B',
          value: 25769803776,
          formatted: '24576 MiB',
        },
      },
      {
        name: '3XL',
        mem: 32768,
        cpus: 16,
        gpus: 0,
        disk: null,
        price: 0.8888888889,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.3XL',
        memory: {
          unit: 'B',
          value: 34359738368,
          formatted: '32768 MiB',
        },
      },
    ],
    defaultFlavor: {
      name: 'XS',
      mem: 1152,
      cpus: 1,
      gpus: 0,
      disk: null,
      price: 0.0222222222,
      available: true,
      microservice: false,
      machine_learning: false,
      nice: 0,
      price_id: 'apps.XS',
      memory: {
        unit: 'B',
        value: 1073741824,
        formatted: '1024 MiB',
      },
    },
    buildFlavor: {
      name: 'M',
      mem: 4096,
      cpus: 4,
      gpus: 0,
      disk: null,
      price: 0.1055555556,
      available: true,
      microservice: false,
      machine_learning: false,
      nice: 0,
      price_id: 'apps.M',
      memory: {
        unit: 'B',
        value: 4294967296,
        formatted: '4096 MiB',
      },
    },
  },
  {
    type: 'java',
    version: '20231110',
    name: 'Scala + SBT',
    variant: {
      id: '75eccbb4-3477-4846-95c5-7471a6bde653',
      slug: 'sbt',
      name: 'Scala + SBT',
      deployType: 'java',
      logo: 'https://assets.clever-cloud.com/logos/scala.svg',
    },
    description: 'java',
    enabled: true,
    comingSoon: false,
    maxInstances: 40,
    tags: [
      'gradle',
      'jar',
      'java',
      'jvm',
      'maven',
      'mvn',
      'play',
      'sbt',
      'war',
    ],
    deployments: [
      'git',
    ],
    flavors: [
      {
        name: 'pico',
        mem: 326,
        cpus: 1,
        gpus: 0,
        disk: null,
        price: 0.0062500000,
        available: true,
        microservice: true,
        machine_learning: false,
        nice: 5,
        price_id: 'apps.pico',
        memory: {
          unit: 'B',
          value: 268435456,
          formatted: '256 MiB',
        },
      },
      {
        name: 'nano',
        mem: 582,
        cpus: 1,
        gpus: 0,
        disk: null,
        price: 0.0083333333,
        available: true,
        microservice: true,
        machine_learning: false,
        nice: 5,
        price_id: 'apps.nano',
        memory: {
          unit: 'B',
          value: 536870912,
          formatted: '512 MiB',
        },
      },
      {
        name: 'XS',
        mem: 1152,
        cpus: 1,
        gpus: 0,
        disk: null,
        price: 0.0222222222,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.XS',
        memory: {
          unit: 'B',
          value: 1073741824,
          formatted: '1024 MiB',
        },
      },
      {
        name: 'S',
        mem: 2048,
        cpus: 2,
        gpus: 0,
        disk: null,
        price: 0.0444444444,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.S',
        memory: {
          unit: 'B',
          value: 2147483648,
          formatted: '2048 MiB',
        },
      },
      {
        name: 'M',
        mem: 4096,
        cpus: 4,
        gpus: 0,
        disk: null,
        price: 0.1055555556,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.M',
        memory: {
          unit: 'B',
          value: 4294967296,
          formatted: '4096 MiB',
        },
      },
      {
        name: 'L',
        mem: 8192,
        cpus: 6,
        gpus: 0,
        disk: null,
        price: 0.2111111111,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.L',
        memory: {
          unit: 'B',
          value: 8589934592,
          formatted: '8192 MiB',
        },
      },
      {
        name: 'XL',
        mem: 16384,
        cpus: 8,
        gpus: 0,
        disk: null,
        price: 0.4222222222,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.XL',
        memory: {
          unit: 'B',
          value: 17179869184,
          formatted: '16384 MiB',
        },
      },
      {
        name: '2XL',
        mem: 24576,
        cpus: 12,
        gpus: 0,
        disk: null,
        price: 0.6666666667,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.2XL',
        memory: {
          unit: 'B',
          value: 25769803776,
          formatted: '24576 MiB',
        },
      },
      {
        name: '3XL',
        mem: 32768,
        cpus: 16,
        gpus: 0,
        disk: null,
        price: 0.8888888889,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.3XL',
        memory: {
          unit: 'B',
          value: 34359738368,
          formatted: '32768 MiB',
        },
      },
    ],
    defaultFlavor: {
      name: 'XS',
      mem: 1152,
      cpus: 1,
      gpus: 0,
      disk: null,
      price: 0.0222222222,
      available: true,
      microservice: false,
      machine_learning: false,
      nice: 0,
      price_id: 'apps.XS',
      memory: {
        unit: 'B',
        value: 1073741824,
        formatted: '1024 MiB',
      },
    },
    buildFlavor: {
      name: 'M',
      mem: 4096,
      cpus: 4,
      gpus: 0,
      disk: null,
      price: 0.1055555556,
      available: true,
      microservice: false,
      machine_learning: false,
      nice: 0,
      price_id: 'apps.M',
      memory: {
        unit: 'B',
        value: 4294967296,
        formatted: '4096 MiB',
      },
    },
  },
  {
    type: 'java',
    version: '20231110',
    name: 'Java + WAR',
    variant: {
      id: '05d5db48-b35d-4bf4-b41b-3d6c25f48b69',
      slug: 'war',
      name: 'Java + WAR',
      deployType: 'java',
      logo: 'https://assets.clever-cloud.com/logos/java-war.svg',
    },
    description: 'java',
    enabled: true,
    comingSoon: false,
    maxInstances: 40,
    tags: [
      'gradle',
      'jar',
      'java',
      'jvm',
      'maven',
      'mvn',
      'play',
      'sbt',
      'war',
    ],
    deployments: [
      'git',
    ],
    flavors: [
      {
        name: 'pico',
        mem: 326,
        cpus: 1,
        gpus: 0,
        disk: null,
        price: 0.0062500000,
        available: true,
        microservice: true,
        machine_learning: false,
        nice: 5,
        price_id: 'apps.pico',
        memory: {
          unit: 'B',
          value: 268435456,
          formatted: '256 MiB',
        },
      },
      {
        name: 'nano',
        mem: 582,
        cpus: 1,
        gpus: 0,
        disk: null,
        price: 0.0083333333,
        available: true,
        microservice: true,
        machine_learning: false,
        nice: 5,
        price_id: 'apps.nano',
        memory: {
          unit: 'B',
          value: 536870912,
          formatted: '512 MiB',
        },
      },
      {
        name: 'XS',
        mem: 1152,
        cpus: 1,
        gpus: 0,
        disk: null,
        price: 0.0222222222,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.XS',
        memory: {
          unit: 'B',
          value: 1073741824,
          formatted: '1024 MiB',
        },
      },
      {
        name: 'S',
        mem: 2048,
        cpus: 2,
        gpus: 0,
        disk: null,
        price: 0.0444444444,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.S',
        memory: {
          unit: 'B',
          value: 2147483648,
          formatted: '2048 MiB',
        },
      },
      {
        name: 'M',
        mem: 4096,
        cpus: 4,
        gpus: 0,
        disk: null,
        price: 0.1055555556,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.M',
        memory: {
          unit: 'B',
          value: 4294967296,
          formatted: '4096 MiB',
        },
      },
      {
        name: 'L',
        mem: 8192,
        cpus: 6,
        gpus: 0,
        disk: null,
        price: 0.2111111111,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.L',
        memory: {
          unit: 'B',
          value: 8589934592,
          formatted: '8192 MiB',
        },
      },
      {
        name: 'XL',
        mem: 16384,
        cpus: 8,
        gpus: 0,
        disk: null,
        price: 0.4222222222,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.XL',
        memory: {
          unit: 'B',
          value: 17179869184,
          formatted: '16384 MiB',
        },
      },
      {
        name: '2XL',
        mem: 24576,
        cpus: 12,
        gpus: 0,
        disk: null,
        price: 0.6666666667,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.2XL',
        memory: {
          unit: 'B',
          value: 25769803776,
          formatted: '24576 MiB',
        },
      },
      {
        name: '3XL',
        mem: 32768,
        cpus: 16,
        gpus: 0,
        disk: null,
        price: 0.8888888889,
        available: true,
        microservice: false,
        machine_learning: false,
        nice: 0,
        price_id: 'apps.3XL',
        memory: {
          unit: 'B',
          value: 34359738368,
          formatted: '32768 MiB',
        },
      },
    ],
    defaultFlavor: {
      name: 'XS',
      mem: 1152,
      cpus: 1,
      gpus: 0,
      disk: null,
      price: 0.0222222222,
      available: true,
      microservice: false,
      machine_learning: false,
      nice: 0,
      price_id: 'apps.XS',
      memory: {
        unit: 'B',
        value: 1073741824,
        formatted: '1024 MiB',
      },
    },
    buildFlavor: {
      name: 'M',
      mem: 4096,
      cpus: 4,
      gpus: 0,
      disk: null,
      price: 0.1055555556,
      available: true,
      microservice: false,
      machine_learning: false,
      nice: 0,
      price_id: 'apps.M',
      memory: {
        unit: 'B',
        value: 4294967296,
        formatted: '4096 MiB',
      },
    },
  },
];
/* eslint-enable camelcase */

export const APP_TYPES_AND_SLUGS = APP_PROVIDERS_RAW.map((app) => {
  return {
    type: app.type,
    slug: app.variant.slug,
  };
});

export const getAppFromTypeAndSlug = (appId) => APP_PROVIDERS_RAW.find((app) => app.type === appId.type && app.variant.slug === appId.slug);
