name: Compute number of shards

concurrency:
  group: visual-changes-${{ inputs.pr_number || inputs.branch }}
  cancel-in-progress: true

on:
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  calculate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: '[Prepare] Checkout'
        uses: actions/checkout@v4

      - name: '[Prepare] Setup Node.js'
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'npm'
      - run: npm ci

      - id: set-matrix
        run: |
          echo "matrix=$(node ./tasks/get-number-of-visual-batches.js)" >> $GITHUB_OUTPUT

  run-visual-tests:
    needs: calculate-matrix
    uses: ./.github/workflows/visual-regression-tests.yml
    secrets: inherit
    permissions:
      contents: write
      pull-requests: write
    with:
      matrix: ${{ needs.calculate-matrix.outputs.matrix }}
      branch: ${{ github.head_ref }}
      pr_number: ${{ github.event.pull_request.number }}
      base_sha: ${{ github.event.pull_request.base.sha }}
