name: Tests and build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: '[Prepare] Checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: '[Prepare] Setup Node.js'
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
          cache: 'npm'
      - name: '[Prepare] Install dependencies'
        run: npm ci

      - name: '[Code quality] Check commit message'
        if: github.event_name == 'pull_request'
        run: node ./node_modules/@commitlint/cli/cli.js --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
      - name: '[Code quality] Check ESLint'
        run: npm run lint
      - name: '[Code quality] Check Lit'
        run: npm run components:check-lit
      - name: '[Code quality] Check types'
        run: npm run typecheck
      - name: '[Code quality] Check types imports'
        run: npm run components:check-type-imports
      - name: '[Code quality] Check Stylelint'
        run: npm run stylelint
      - name: '[Code quality] Check Prettier (formatting)'
        run: npm run format:check
      - name: '[Code quality] Check i18n'
        run: npm run components:check-i18n

      - name: '[Code Generation] Check global events map'
        run: npm run components:events-map-check

      - name: '[Unit tests] Clever components'
        run: npm run test
      - name: '[Unit tests] Mocha tests (CEM, ESLint & Prettier custom rules)'
        run: npm run test:mocha

      - name: '[Build] Clever components'
        run: npm run components:build
      - name: '[Build] Documentation'
        run: npm run components:docs
      - name: '[Build] CDN'
        run: VERSION=0.0.0 npm run cdn-release:build
