name: Tests and build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: '[Prepare] Checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: '[Prepare] Setup Node.js'
        uses: volta-cli/action@v4
      - name: '[Prepare] Install dependencies'
        run: npm ci

      - name: '[Code quality] Check ESLint'
        run: npm run lint
      - name: '[Code quality] Check Lit'
        run: npm run components:check-lit
      - name: '[Code quality] Check types'
        run: npm run typecheck
      - name: '[Code quality] Check types imports'
        run: npm run components:check-type-imports
      - name: '[Code quality] Check Stylelint'
        run: npm run stylelint:ci
      - name: '[Code quality] Check i18n'
        run: npm run components:check-i18n

      - name: '[Unit tests] Clever components'
        run: npm run test
      - name: '[Unit tests] Custom element manifest generation'
        run: npm run test:cem

      - name: '[Build] Clever components'
        run: npm run components:build
      - name: '[Build] Documentation'
        run: npm run components:docs
      - name: '[Build] CDN'
        run: VERSION=0.0.0 npm run cdn-release:build
