name: Visual Regression Tests

on:
  pull_request:
    types: [synchronize, opened, reopened, labeled, unlabeled]

jobs:
  run-test-visual-regression-tests:
    if: ${{ !contains(join(fromJson(toJson(github.event.pull_request.labels)).*.name, ','), 'test-visual-regressions:skip') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: '[Prepare] Setup Node.js'
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
          cache: 'npm'
      - name: '[Prepare] Install dependencies'
        run: npm ci

      - name: '[Prepare] Install Playwright Browsers'
        run: npx playwright install --with-deps

      - name: 'Run Visual Regression Tests'
        run: npm run test-visual-regressions
